let mapleader = " "
set number
set relativenumber
set cursorline
set noswapfile
set autoindent
set smartindent
set clipboard^=unnamed,unnamedplus
set scrolloff=5
set incsearch


inoremap <esc> <nop>
inoremap jk <esc>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>

nnoremap <c-w>h <c-w><c-h>
nnoremap <c-w>j <c-w><c-j>
nnoremap <c-w>k <c-w><c-k>
nnoremap <c-w>l <c-w><c-l>

nnoremap H 0
nnoremap J $
nnoremap <leader>ev :vsplit $MYVIMRC<cr>
nnoremap <leader>sv :write<cr>:source $MYVIMRC<cr>
nnoremap <leader>pi :PlugInstall<cr>
nnoremap <leader>" viw<esc>a"<esc>hbi"<esc>lel
nnoremap <leader>' viw<esc>a'<esc>hbi'<esc>lel
nnoremap <leader>o :only<cr>
vnoremap <leader>' <esc>`<<esc>i'<esc>`>la'<esc>


call plug#begin()
Plug 'morhetz/gruvbox'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
call plug#end()

if (has("termguicolors"))
	set bg=dark
	set termguicolors
	let g:gruvbox_contrast_dark='soft'
	colorscheme gruvbox
endif

augroup filetype_html
	autocmd!
	autocmd FileType html nnoremap <buffer> <localleader>f Vatzf
augroup END


onoremap p i(
onoremap b /return<cr>
onoremap in( :<c-u>normal! f(vi(<cr>
onoremap an( :<c-u>normal! f(va(<cr>

augroup filetype_markdown
	autocmd!
	autocmd FileType markdown onoremap <buffer> ih :<c-u>execute "normal! ?^==\\+$\r:nohlsearch\rkvg_"<cr>
	autocmd FileType markdown onoremap <buffer> ah :<c-u>execute "normal! ?^==\\+$\r:nohlsearch\rg_vk0"<cr>
augroup END

" Vimscript file settings ---------------------- {{{
augroup filetype_vim
	autocmd!
	autocmd FileType vim setlocal foldmethod=marker
augroup END
" }}}